application/views/dashboard.py
from flask import Flask, Blueprint, render_template, url_for, request, session, redirect
from login import logged_in
from ..models import tables, History, Orders, Employees, Products, Customers, ORDER_STATUS_ON_RESERVE 
from ..restrictions import * 
dashboard_page = Blueprint('dashboard', __name__, template_folder='../templates')

@dashboard_page.route('/dashboard')
def show():
    if logged_in():
        # Get the reserve data, and any data needed to populate the dashboard
        # and pass in into the params
        reserve = get_orders_on_reserve()
        role = get_role(session['email'])
        tables = get_tables(role)
        columns = reserve['columns']
        history = get_history(limit=5)
        params = dict(title_name='Dashboard', tables=tables, reserve = reserve['rows'], columns=columns, history=history)
        return render_template('dashboard.html', **params)
    else:
        return redirect(url_for('login.show'))

def get_orders_on_reserve():
    reserve = {}
    orders = []
    objs = Orders.query.filter_by(status=ORDER_STATUS_ON_RESERVE).all()
    for obj in objs:
        order = {}
        customer = get_customer_by_id(obj.customer_id)
        product = get_product_by_id(obj.product_id)
        order['name'] = customer.firstname.capitalize() + " " + customer.lastname.capitalize() 
        order['product'] = product.product_name
        order['phone'] = customer.phone
        order['comments'] = obj.comments
        orders.append(order)
    reserve['columns'] = map(lambda x: x.capitalize(), ['phone', 'product', 'name', 'comments'])
    reserve['rows'] = orders
    return reserve 


def get_customer_by_id(id):
    return Customers.query.get(id)

def get_product_by_id(id):
    return Products.query.get(id)

def get_employee_by_id(id):
    return Employees.query.get(id)

def get_history(limit=5):
    history = History.query.order_by(History.date.desc()).limit(limit).all()
    history_list = []
    for h in history:
        emp = get_employee_by_id(h.employee_id)
        if h.operation == "delete":
            string = emp.name.capitalize() + " " +  h.operation + "d a record on the " + h.table + " table at " + h.date  
        elif h.operation != "delete":
            string = emp.name.capitalize() + " " +  h.operation + "ed a record on the " + h.table + " table at " + h.date 
        history_list.append(string) 
    return history_list

application/views/help.py
from flask import Flask, Blueprint, render_template, url_for, request, session, redirect
from ..models import tables
from ..restrictions import * 
from login import logged_in

help_page = Blueprint('help', __name__, template_folder='../templates')

@help_page.route('/help')
def show():
    if not logged_in():
	    return redirect(url_for('login.show'))
    role = get_role(session['email'])
    tables = get_tables(role)
    params = dict(title_name='Help', tables=tables)
    return render_template('help.html', **params)

application/views/login.py
from flask import Flask, Blueprint, render_template, url_for, request, session, redirect
from .. import utils
from ..models import Employees 
from ..database import db
from ..restrictions import get_role

login_page = Blueprint('login', __name__, template_folder='../templates', static_folder="static")

@login_page.route('/login', methods=['GET', 'POST'])
def show():
    params = dict(title_name='Login');
    if request.method == 'POST':
        error = False
        email = request.form['email']
        password = request.form['password']
        if email is session:
            return redirect(url_for("index.show"))
        params['email'] = email # this will be returned back to the page

        if not utils.valid_password(password):
            params['pw_info'] = "Incorrect password"
        if not user_exists(email):
            params['user_info'] = "Incorrect email"
            error = True
        else:
            valid_pw = valid_pw_for(email, password)
            if not valid_pw:
                params['user_info'] = "Incorrect email"
                error = True
        if not email:
            params['user_info'] = "Incorrect email"
            error = True
        if error:
            params['info_class'] = 'errorDisplay'
            return render_template("login.html", **params)
        else:
            session['email'] = email 
            return redirect(url_for("index.show"))
    else:
        if logged_in():
            return redirect(url_for("index.show"))
        return render_template("login.html", **params)


@login_page.route('/logout')
def logout():
    session.pop('email', None)
    return redirect(url_for('login.show'))

def logged_in():
    if 'email' in session:
        if get_role(session['email']) is None:
            return False
        return True
    return False

def user_exists(email):
	email = utils.normalize(email)
	exists = Employees.query.filter_by(email=email).first()
	if exists is None:
	    return False
	return True 

def valid_pw_for(email, password):
	if email and password:
		h, salt = get_user_pw(utils.normalize(email))
		return utils.check_password(h, salt, password) 
	return False

def get_user_pw(email):
	if email:
		email = utils.normalize(email)
		u = Employees.query.filter_by(email=email).first()
		return (u.hash, u.salt)
	return None

def change_password(email, old_password, new_password):
    if not logged_in():
        return False
    error = False
    email = utils.normalize(email)
    if not utils.valid_password(new_password):
        error = True
    if not valid_pw_for(email, old_password):
        error = True
    if old_password == new_password:
        error = True
    if error:
	    return False
    else:
        employee = Employees.query.filter_by(email=email).first()
        h = utils.gen_hash(new_password)
        salt , h = utils.get_salt_hash(h)
	employee.hash = h
	employee.salt = salt
	db.session.commit()
	return True

def change_email(old_email, new_email, password):
    if not logged_in():
        return False
    error = False
    old_email = utils.normalize(old_email)
    new_email = utils.normalize(new_email)
    if not utils.valid_email(new_email):
        error = True
    if user_exists(new_email):
        error = True
    if not valid_pw_for(old_email, password):
        error = True  
    if error:
        return False
    else:
	#change email 
        employee = Employees.query.filter_by(email=old_email).first()
	employee.email = new_email 
	db.session.commit()
	logout()
	session['email'] = new_email
	return True

application/views/order.py
from flask import Flask, Blueprint, request, abort, render_template
import datetime
from ..models import Orders, Customers, Products, ORDER_STATUS_ON_RESERVE
from ..database import db
from ..utils import normalize

order_form = Blueprint('order', __name__, template_folder='../templates', static_folder='static')
required_fields = ['first_name', 'last_name', 'email', 'product_id', 'street', 'postal_code', 'town', 'phone']

@order_form.route('/order', methods=['GET', 'POST'])
def show():
    params = dict(title_name='Order Form')
    if request.method == 'POST':
        params = set_params(params, request)
        if is_valid_order(request):
            date = datetime.datetime.utcnow()
            product_id = request.form['product_id']
            comments = request.form['comments']    
            email = request.form['email'] 
            customer_id = None
            prod_exists = None
            customer_obj = get_customer_if_exists(email)
                    # check if customer already exists
            if product_id:
               prod_exists = product_exists(product_id)
            if customer_obj:
                # if it does then find his id and link to the order
                customer_id = customer_obj.id
            else:
                # if not then add the customer to the database first. 
                first_name = request.form['first_name']
                last_name = request.form['last_name']
                street = request.form['street']
                postal_code = request.form['postal_code']
                town = request.form['town']
                phone = request.form['phone']
                new_customer = Customers(first_name, last_name, email, street, postal_code, town, phone)
                db.session.add(new_customer) 
                db.session.commit()
                customer_id = new_customer.id
            # do a final check to see if the customer exists
            if customer_id is None or prod_exists is None:
                params['error'] = "That product doesn't exist"
                return render_template('order_form.html',**params)
            # add the order to the database and link the customer
            new_order = Orders(ORDER_STATUS_ON_RESERVE, date, comments, customer_id, product_id)
            db.session.add(new_order)
            db.session.commit()
            return render_template('thanks.html')
        else: # the order is not valid
            return render_template('order_form.html',**params)
    else:
        return render_template('order_form.html',**params)

def is_valid_order(request):
    """ Basic check to see if the fields is empty """
    is_valid = True
    for field in required_fields:
        if not request.form[field]:
            return False
        return True

def get_customer_if_exists(email):
    email = normalize(email)
    customer = Customers.query.filter_by(email=email).first()
    if customer is None:
        return False
    return customer 

def product_exists(prod_id):
    prod_id = int(prod_id)
    prod = Products.query.get(prod_id)
    return prod
     
def set_params(params, request):
    for field in required_fields:
        params[field] = request.form[field]
    return params

application/views/register.py
from flask import Flask, Blueprint, render_template, url_for, request, session, redirect
from .. import utils
from ..models import Employees
from ..restrictions import *
from ..database import db
from login import user_exists, logged_in

register_page = Blueprint('register', __name__, template_folder='../templates')

@register_page.route('/register', methods=["GET", "POST"])
def show():
	email = None
	try:
	    email = session["email"]
	except KeyError:
		pass
	if logged_in() and is_admin_user(email):
	    params = dict(title_name='Register', roles=ROLES)
	    if request.method == 'POST':
		error = False
		name = request.form['name']
		phone = request.form['phone']
		email = utils.normalize(request.form['email'])
		password = request.form['password']
		verify = request.form['verify']
		r = request.form['restriction']
		params['name'] = name
		params['phone'] = phone
		params['email'] = email
		if not name:
		    params['name_info'] = "The name can't be empty"
		    error = True
		if not phone:
		    params['phone_info'] = "The phone number can't be empty"
		    error = True
		if not utils.valid_email(email):
		    params['email_info'] = "That is not a valid email."
		    error = True
		if not utils.valid_password(password):
		    params['pw_info'] = "That is not a valid password."
		    error = True
		if verify != password:
		    params['verify_info'] = "The passwords don't match."
		    error = True
		if user_exists(email):
		    params['email_info'] = "That email is alredy in use."
		    error = True
		if not r:
		    params['restriction_info'] =  "You need to specify a user type."
	            error = True
		if error:
		    params['info_class'] = 'text-danger'
		    return render_template("register.html", **params)
		else:
		    # put user in database
		    # now we can safely say,
		    # the username, password, email are valid
		    # the usernanme, email are not already in our database
		    h = utils.gen_hash(password)
		    salt , h = utils.get_salt_hash(h)
		    new_user = Employees(name, phone, email, r, h, salt)
		    db.session.add(new_user)
		    db.session.commit()
		    return redirect(url_for("login.show"))
	    else:
		return render_template("register.html", **params)
	else:
	    return redirect(url_for("login.show"))


def is_admin_user(email):
    if email is None:
        return False
    email = normalize(email)
    user = Employees.query.filter_by(email=email).first()
    if user is None:
        return False
    if user.restriction == ADMIN_ROLE:
        return True
    return False
 

application/views/settings.py
from flask import Flask, Blueprint, render_template, url_for, request, redirect, session, make_response 
from ..models import tables
from ..restrictions import * 
from login import logged_in, change_password, change_email

settings_page = Blueprint('settings', __name__, template_folder='../templates')

languages = {
'en' : 'English',
'fr': 'French',
} 

backups = {
'1m' : 'Every month',
'2m' : 'Every 2 months',
'6m' : 'Every 6 months',
'12m': 'Every 12 months'
}

@settings_page.route('/settings', methods=['GET', 'POST'])
def show():
    if not logged_in():
        return redirect(url_for('login.show'))
    role = get_role(session['email'])
    tables = get_tables(role)
    params = dict(title_name='Settings')
    params['role'] = role
    params['tables'] = tables
    params['languages'] = languages
    params['backups'] = backups
 
    if request.method == 'GET':
        return render_template('settings.html', **params)
    elif request.method == 'POST':
	return save_settings(request, params)
    

def save_settings(request, params):
    email_changed = False
    password_changed = False
    lang = get_lang_or_default(request.form['lang'])
    backup = set_backup_time(request.form['backup'])
    params['lang'] = lang
    params['backup'] = backup
    
    new_password = request.form['new_password']
    new_email = request.form['new_email']
    old_password = request.form['password']
    print "new password is" + str(new_password)
    print "new email is" + str(new_email)
    if old_password:
        if new_email:
	    email_changed = change_email(session['email'], new_email, old_password)
	    if email_changed:
     	        params['email_class'] = 'text-success'
	        params['email_info'] = "Email was changed successfully."
	    else:
		params['email_class'] = 'text-danger'
		params['email_info'] = "there was an error changing your email."
        if new_password:
	    password_changed = change_password(session['email'], old_password, new_password)
	    if password_changed:
                params['password_class'] = 'text-success'
		params['pw_info'] = 'Password was changed successfully.'
	    else:
	        params['password_class'] = 'text-danger'
	        params['pw_info'] = "there was an error changing your password."
    else:
	params['old_pw_info'] = 'Your old password is needed'
	params['old_password_class'] = 'text-danger'
	
    resp = make_response(render_template('settings.html', **params))
    resp.set_cookie('lang', lang)
    return resp

def get_lang_or_default(lang):
	if lang not in languages:
		return 'en'
	return lang

def set_backup_time(backup):
	return backup

application/templates/dashboard.html
  {% extends 'base.html' %}
  <html>
  <head>
    {%- block head -%}  
    {{ super() }}
   {% endblock %}</head><body>
  {%  block content %}
	{% include 'side_bar.html' %}
   <form name="dashboardForm" action="{{ url_for('dashboard.show') }}" method="post">
  <div class="container">
  <h2>News</h2>
        <div class="page-content">
            <p>Attention all employees, we will have a meeting this Tuesday in our board room. The meeting will take
            place at 10:00 a.m. We will discuss our upcoming products.</p>
        </div>


      <h2>Reserve List</h2>
   <div class="page-content">
      <table id="reserve">
          <thead>
              <tr>
                  {% for col in columns %}
                      <th>{{col}}</th>
                  {% endfor %}
              </tr>
          </thead>
      
        <tbody>
            {% for item in reserve %}
            <tr>
                {% for key in item.keys() %}
                <td> {{ item[key] }} </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
      </table>

    </div>
<h2>Recent History</h2>
    <div class="page-content">
      <table id="reserve">
          {% for record in history %}
          <tr><td>{{ record }}</td></tr>
          {% endfor %}
     </table>
    </div>
      </div>
</div>

{% endblock %}
{%- block scripts %}
 {{ super() }}
{% endblock %}
</body>
</html>

application/templates/order_form.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
  
  <head>
  {% block head %}  
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/register.css') }}">
  {% endblock %}

    {{ super() }}
  <script type="text/javascript">
       var req = ['first_name', 'last_name', 'email', 'product_id', 'street', 'postal_code', 'town', 'phone'];

       function validate() {
           var form = document.forms['order'];
           var elements = form.elements;
           for (var i = 0; i < req.length; i++) {
               if ( !elements[req[i]].value) {
                   alert('You are need missing fields');
                   return false;
               }
           }
           return true;
       }
       
  </script>
 
</head>

 <body>
  {%  block content %}
   
   <label>
    <img src="{{ url_for('static', filename='img/logo.png') }}" />
    <h1 style='text-align:center;'>{{ title_name }}</h1>
    <div class='row'>
    <form class='form-horizontal col-sm-4 col-sm-offset-4' id="order" action="{{ url_for('order.show') }}" method="post">
	

    <form class='form-horizontal col-sm-4 col-sm-offset-4' id="order" onsubmit="return validate();" action="{{ url_for('order.show') }}" method="post">
        
	
	    <div class='form-group'>
		<div class='col-sm-12'>
	
		<input type='text' class='form-control' name='first_name' value='{{ first_name }}'
		placeholder='First name' autofocus> 



		</div>
		<div class='col-sm-12 {{ info_class }}'><p>{{ first_name_info }}</p></div>

	    </div>
	    <div class='form-group'>
		<div class='col-sm-12'>
		<input type='text' class='form-control' name='last_name' value='{{ last_name }}' placeholder='Last name'> 
		</div>
		<div class='col-sm-12 {{ info_class }}'><p>{{ name_info }}</p></div>
	    </div>
            <div class='form-group'>
		<div class='col-sm-12'>
		<input type='text' class='form-control' name='email' value='{{ email }}' placeholder='Email'> 
		</div>
		<div class='col-sm-12 {{ info_class }}'><p>{{ email_info }}</p></div>
	    </div>
            <div class='form-group'>
		<div class='col-sm-12'>
		<input type='text' class='form-control' name='product_id' value='{{ product_id }}' placeholder='Product'> 
        {% if error %}
        <p style="color:red;" >{{ error }} </p>
        {% endif %}
		</div>
		<div class='col-sm-12 {{ info_class }}'><p>{{ product_info }}</p></div>
	    </div>
	    <div class='form-group'>
		<div class='col-sm-12'>
		<input type='text' class='form-control' name='street' value='{{ street }}' placeholder='Street'> 
		</div>
		<div class='col-sm-12 {{ info_class }}'><p>{{ street_info }}</p></div>
		</div>
	     <div class='form-group'>
		<div class='col-sm-12'>
		<input type='text' class='form-control' name='postal_code' value='{{ postal_code }}' placeholder='Postal Code'> 
		</div>
		<div class='col-sm-12 {{ info_class }}'><p>{{ postal_code_info}}</p></div>
		</div>
 	     <div class='form-group'>
		<div class='col-sm-12'>
		<input type='text' class='form-control' name='town' value='{{ town }}' placeholder='Town'> 
		</div>
		<div class='col-sm-12 {{ info_class }}'><p>{{ town_info }}</p></div>
		</div>
  	     <div class='form-group'>
		<div class='col-sm-12'>
		<input type='tel' class='form-control' name='phone' value='{{ phone }}' placeholder='Phone'> 
		</div>
		<div class='col-sm-12 {{ info_class }}'><p>{{ phone_info }}</p></div>
		</div>
   	     <div class='form-group'>
		<div class='col-sm-12'>
			<textarea class="form-control" name='comments' rows="3" placeholder="Comments">

			</textarea>
		</div>
		</div>
	     <div class='form-group'>
		<div class='col-sm-12'>
		<input id="submitButton" class="btn btn-primary btn-lg btn-block" type="submit" value="Submit Order">
           </div>

           <br>
           <br>
           <br>
    </form>

    </label>
  {%  endblock %}
  </body>
</html>

application/templates/register.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>

  {% block head %}  
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/register.css') }}">
  {% endblock %}

<body>
  {% block content %}

  <label>
   <h1 id='form-title'>Sign Up</h1>

   <form class="form-horizontal"action="{{ url_for('register.show') }}" method="post">
  
    <input type='text' class='form-control' name='name' value='{{ name }}' placeholder='John Smith' autofocus> <div class='col-lg-3 {{ info_class }}'><p>{{ name_info }}</p></div>

    <input type='text' class='form-control' name='name' value='{{ name }}' placeholder='John Smith'> <div class='col-lg-3 {{ info_class }}'><p>{{ name_info }}</p></div>


    <input type='text' class='form-control' name='email' value='{{ email }}' placeholder='johnsmith@example.com'> 
    <div class='col-lg-3 {{ info_class }}'><p>{{ email_info }}</p></div>

    <input type='text' class='form-control' name='phone' value='{{ phone }}' placeholder='514-123-4567'> 
    <div class='col-lg-3 {{ info_class }}'><p>{{ phone_info }}</p></div>


    <input type='password' class='form-control' name='password' placeholder='Password'> 
    <div class='col-lg-3 {{ info_class }}'><p>{{ pw_info }}</p></div>


    <input type='password' class='form-control' name='verify' placeholder='Confirm password'> 
    <div class='col-lg-3 {{ info_class }}'><p>{{ verify_info }}</p></div>

    <select name="restriction">
     {% for r in roles %}
     <option value="{{ r }}">{{ r.split('_')[0].capitalize() }}</option>
     {% endfor %}
   </select>

   <input class="btn btn-primary btn-lg btn-block" type="submit" value="Sign up">
   <div class='col-lg-3 {{ info_class }}'><p>{{ restriction_info }}</p></div>

 </form>

</label>

{% endblock %}
<body>
  </html>

application/templates/settings.html
{% extends 'base.html' %}
  <html>
  <head>
    {% block head %}  
    {{ super() }}
{% endblock %}
</head>
<body>
  {%  block content %}
  {% include 'side_bar.html' %}
  <form name="settingsForm" action="{{ url_for('settings.show') }}" method="post">
  <div class="container">
   <div >
      <h3>General Settings</h3>
      <nav class="page-content"
      role="navigation">
       <h4>Languages:
       <select name="lang">
	{% for l in languages.keys() %}
	<option value="{{ l }}">{{ languages[l] }}</option>
        {% endfor %}	
      </select>
    </h4>
       <h4>Backup: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <select name="backup">
	{% for b in backups.keys() %}
	<option value="{{ b }}">{{ backups[b] }}</option>
	{% endfor %}
      </select>
       </h4>
     </div>
   </div>

     <div>
     <div class="container">
     <h3>User Settings</h3>
     <nav class="page-content"
      role="navigation">  
 
      <h4>Change Password</h4><input type="password" class="form-control" name="new_password"/>
      <p class="{{ password_class }}">{{ pw_info }}</p>
      
      <h4>Change E-mail</h4><input type="email" class="form-control"  name="new_email"/>
      <p class="{{ email_class }}">{{ email_info }}</p>

      <h4>Old password</h4><input type="password" class="form-control"  name="password"/>
      <p style="margin-top:20px"class="">Please type your old password (only if you are changing your email or password)</br>Keep blank if you are not doing anything</p>

      <p class="{{ old_password_class }}">{{ old_pw_info }}</p>
     </div>
   </div>

     <div>
     <div class="container">
     <h3>User Permissions</h3>
     <nav class="page-content 
      role="navigation">
       <h4>User Type: {{ role.split('_')[0].capitalize() }}</h4>
       <h5>Has access to</h5>
       <ul>
       {% for t in tables %}

       <li>{{ t.capitalize() }}</li> 
       {% endfor %}
       <ul>
         </nav>
	   <button type="submit" class="settingsButton">Save Changes</button>
	   <button type="button" class="settingsButton">Restore Default Settings</button>
     </div>
   
   </div>

  </form>
  {% endblock %}
   </body>
   </html>

application/templates/side_bar.html
  <!DOCTYPE html>
  <html>
  <head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.sidr.light.css') }}">
</head>

<body>
<a id="simple-menu" href="#sidr"><img id="menuToggle" src="{{ url_for('static', filename='img/arrow2.png') }}"></a>
    <div id="sidr">
    <img id="img" src="{{ url_for('static', filename='img/logo.png') }}">
    <ul>
    <li><a href="{{ url_for('dashboard.show') }} ">Dashboard</a></li>
     {% for key in tables %}
         <li><a href="{{ url_for('table_template.show',table=key) }}">{{ key.capitalize() }}</a></li>
     {% endfor %}
  <li><a href="{{ url_for('settings.show') }}">Settings <span class="glyphicon glyphicon-cog"></span></a></li>
  <li><a href="{{ url_for('help.show') }}">Help <span class="glyphicon glyphicon-briefcase"></span></a></li>
  <li><a href="{{ url_for('login.logout') }}">Logout <span class="glyphicon glyphicon-log-out"></span></a></li>
  <li></li>
    </ul>
  </div>
 </body>
</html>

application/templates/table_template.html
  {% extends 'base.html' %}
  <html>
  <head>
    {% block head %}  
    {{ super() }}
    <style>
        @media print {
            #sidr,
            #simple-menu,
            #nav-operation,
            #datatable_length, #datatable_filter,
            input[name="row_select"], #datatable_info,
            #datatable_paginate , .operation-form{
                display:none;
                visibility:hidden; 
            }

            #page-title {
                margin:0px !important;
                padding:5px !important;
                margin-bottom:10px;
            }
            #table_div {
                width: 100%;
            }
            .container {
                width:1000px;
                margin:5px !important;
            }
            body {
                margin:0px;
                padding:0px;
                width:100%;
               position:relative;
               left:0px !important; 
            }
            body * {
                margin:0px;
                padding:0px;
            }
        }
    
    </style>
    {% endblock %}
</head>
<body>
  {%  block content %}
   {% include 'side_bar.html' %}
   <div class="container">
    <h2 id="page-title">{{ table_name }}</h2>
      <nav id="nav-operation" class="navbar" role="navigation">
       <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
        <ul class="nav navbar-nav">
		{% for op in operations %}
        <li id="{{ op.lower() + '-op' }}">
            {% if op.lower() == 'add' %}
                {% if table_name == 'Employees' %}
                    <a href="{{ url_for('register.show')}}">{{op.capitalize() }} 
                {% elif table_name == 'Orders' %}
                    <a href="{{ url_for('order.show')}}">{{op.capitalize() }} 
                {% else %}
                    <a href="#">{{op.capitalize() }} 
                {% endif %}
            {% else %}
                    <a href="#">{{op.capitalize() }} 
            {% endif %}
                
                <span class="{{ css_icons[op] }}"></span>
            </a>
        </li>
		{% endfor %}
        <li>
        <a id="print-op" href="#">Print <span class="glyphicon glyphicon-print"></span></a> 
        </li>
       </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div id="page-content">
    <form id="add-form" role="form" class="operation-form" class="operation-form" style="display:none;" >
      {% for inp in forms %}
      <div class="form-group">
	      <label for="{{inp.name}}">{{ inp.label }}</label>
	      <input type="{{inp.type}}" class="form-control" id="{{inp.name}}">
     </div>
      {% endfor %}
  <button id="add-btn" type="button" class="btn btn-primary operationButton">Add</button>
   </form>
   
   <form id="edit-form" role="form" class="operation-form" class="operation-form" style="display:none;" >
      {% for inp in forms %}
      <div class="form-group">
	      <label for="{{inp.name}}">{{ inp.label }}</label>
	      <input type="{{inp.type}}" class="form-control" id="{{inp.name}}">
     </div>
      {% endfor %}
      <button id='edit-previous' type="button" class="btn btn-default">Previous</button>
      <button id='edit-next' type="button" class="btn btn-default">Next</button>
  <button id="edit-btn" type="button" class="btn btn-primary operationButton">Edit</button>
   </form>


   <form id="delete-form" role="form" class="operation-form" class="operation-form" style="display:none;">
    {% for inp in forms %}
    <h4>{{ inp.label }}:<span id="{{inp.name}}"></span></h4>
    {% endfor %}
    <button id='delete-previous' type="button" class="btn btn-default">Previous</button>
     <button id='delete-next' type="button" class="btn btn-default">Next</button>
 
    <button id="delete-btn" type="button" class="btn btn-primary operationButton">Delete</button>
  </form>
  <div id="import-form" role="form" class="operation-form" class="form-group" style="display:none;">
      <label for="import">File input</label>
      <input type="file" id="import-op">
      <p id="file-help" class="help-block"></p>
      <button id="import-btn" type="button" class="btn btn-primary operationButton">Upload</button>
  </div>

  <div id="export-form" class="form-group operation-form" role="form" style="display:none;">
      <label for="export">Export as</label>
	  <select id="export">
			  {% for file in export_files %}
			   <option value="{{ file }}">{{ file }}</option>
			  {% endfor %}
	  </select>
      <button id="export-btn" type="button" class="btn btn-primary operationButton">Export</button>
  </div>
<div  id="tablediv" class="panel panel-default">
<table id="datatable" class="db-table table tablesorter">
   <thead>
      <tr>
         <th></th>
	 {% for col in columns %}
	 <th>{{ col.capitalize() }}</th>
	 {% endfor %}
      </tr>
   </thead>
   <tbody>
      {% for row in payload %}
      <tr>
	   <td><input name="row_select" type="checkbox"/></td>
	   {% for td in columns %}
       <td id="{{td}}">{{ row.__dict__[td] }}</td>
	   {% endfor %}
      </tr>
      {% endfor %}
        </tbody>
</table>
</div>
</div>
</div>
</div>
</div>
{% endblock %}
</body>
{%- block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
    </script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script type="text/javascript"> 
        var columns = [];
        {% for col in columns %}
        columns.push('{{ col }}');
        {% endfor %}
        var colArgs = [];
        colArgs.push({"data": "input"});
        for (var i in columns) {
            colArgs.push({"data": columns[i]}); 
        }
        $("#datatable").dataTable({
                "columns": colArgs
        });
       </script>
{% endblock %}
</html>

application/templates/thanks.html
<html>
    <head>
        <title>Thank you!</title>
    </head>
    <body>
        <h1>Thanks for making an order!</h1>
    </body>
</html>